### ISSUE TITLE
initDB.php fails due to bug in install/pakiti.sql: `regex` column removed but used in INSERT INTO

### ISSUE THREAD

**Issue by bluikko** [CESNET/pakiti3#104]
In commit 25bf03bb5dc24a594d1b2d230e70ccd6ca7f47c2, the `regex` column was removed from `OsGroup` table. But the next line after the `OsGroup` and `OsOsGroup` table definitions in `install/pakiti.sql` tries to INSERT INTO using the `regex` column:

> insert into OsGroup (``name``, `regex`) values ('unknown', '');

Obviously this leads to `install/initDB.php` to exit with error:

> Running the SQL queries ... ERROR: Cannot execute the database definition SQL query (insert into OsGroup (`name`, `regex`) values ('unknown', '')): Unknown column 'regex' in 'field list'

Perhaps the INSERT INTO should be modified to skip adding empty string to the no longer existing `regex` column.

**Edit:** after manually fixing that issue, there's a second issue on `pakiti.sql`:

The table `Cve` is created before table `CveDef`, but the table `Cve` has FOREIGN KEY in table `CveDef`.
So obviously the table `CveDef` must be created before the table `Cve` and not after.

After these two issues were fixed, `initDB.php` succeeded.

**Comment by kouril** [comment]
The problem has been fixed in the code, thanks for reporting it.

Daniel
