### ISSUE TITLE
When rpm binary is installed on Debian system, then the pakiti-client doesn't gather packages

### ISSUE THREAD

**Issue by tauceti2** [CESNET/pakiti3#31]
Even if I set --dpkg-query option with path to the dpkg-query binary, the next condition simply fall into the rpm branch, because rpm binary is found on the system.

235: $cmd = $Option{"rpm"};
236:    if ($cmd) {

I think if the rpm doesn't return any packages and dpkg-query is available then it should be check as well.

**Comment by LionelCons** [comment]
This happens only with a system having both rpm and dpkg-query installed, right?

You should be able to force pakiti-client to ignore the rpm command by giving it the option:

`--rpm ''
`

Would this solve your problem?

**Comment by tauceti2** [comment]
Hi Lionel,

Dne 27.10.2016 v 12:43 Lionel Cons napsal(a):
> This happens only with a system having both rpm and dpkg-query
> installed, right?
> 
> You should be able to force pakiti-client to ignore the rpm command by
> giving it the option:
> 
> |--rpm ''
> |
> 
> Would this solve your problem?

Probably yes, but this is not a nice solution. Wouldn't be nicer to
check the output of rpm or dpkg-query if it returns any data?

Cheers,

Michal P.

**Comment by LionelCons** [comment]
IMHO, systems with both rpm and dpkg-query installed should be quite uncommon. So my preference is to leave it up to the user to decide which tool he wants to base the Pakiti reports on, via the use of the --rpm flag or not.

Of course, we could change the current behavior and add some code to deal with these uncommon cases. My worry is that it will not catch all the cases and the ultimate decision will stay with a human being.

Cases to consider are 9: for both rpm and dpkg-query (when present), they could return:
 - an error (non 0 exit)
 - no output
 - some output

In your view, what should pakiti-client do in these 9 cases?

**Comment by tauceti2** [comment]
I think it should try both, so if it get some output and exit code 0, than it doesn't need to check the second option. If it gets no output or non 0 exit code, than it should check the second option. I don't think we need to cover all 9 cases separately. The other solution is to modify command-line options , rename current --rpm option to --rpm-bin and --dpkg-query to --dpkg-query-bin and add options --rpm and --deb which will force use of rpm o dpkg.

**Comment by kouril** [comment]
A great number of our machines exposes both rpm and dpkg managers, therefore we need the client to behave gracefully without manual intervention. I've provided the appropriate changes in e2c4667.
