### ISSUE TITLE
Howto import CVE data

### ISSUE THREAD

**Issue by ukastens** [CESNET/pakiti3#39]
Is there any URL one could use for importing the CVE data? 
Should be as example in the docs

**Comment by tauceti2** [comment]
Hi,

Thanks for comment. We are using OVAL descriptions from RedHat: https://www.redhat.com/security/data/oval/. I will add it to the docs.

Cheers

**Comment by kouril** [comment]
The documentation was updated a while ago, see e.g. https://github.com/CESNET/pakiti3/blob/master/docs/configuration.md#vulnerability-definition-system.
