### ISSUE TITLE
Configuration issue?

### ISSUE THREAD

**Issue by tjones136** [CESNET/pakiti3#42]
Keep seeing this when attempting to send data from a client:

[error] [client ::1] FastCGI: server "/var/www/cgi-bin/php-cgi-5.5.21" stderr: PHP Catchable fatal error:  Argument 1 passed to HostGroupDao::create() must be an instance of HostGroup, null given, called in /var/www/pakiti3/lib/managers/HostGroupsManager.php on line 51 and defined in /var/www/pakiti3/lib/dao/HostGroupDao.php on line 37

Not sure where I'm supposed to set HostGroup on the client side, or even if I'm supposed to do it there.

**Comment by kouril** [comment]
I believe the issue you reported was fixed by the set of changes that were merged yesterday. Please update your installation and try again.

**Comment by tjones136** [comment]
The update fixed the issue.  Thanks!
