### ISSUE TITLE
OVAL data

### ISSUE THREAD

**Issue by tjones136** [CESNET/pakiti3#47]
Perhaps I'm being a bit thick here, but I can't seem to figure out how to pull the RH OVAL data and get it into my database.

**Comment by mlcit** [comment]
Hi,

You can use cli module vds,php or now after #51 you can add CVE source via gui in VDS tab.
- for example: https://www.redhat.com/security/data/oval/com.redhat.rhsa-2017.xml

After both you have to use cli module for synchronize and recalculateVulnerabilities.

php /var/www/pakiti3/lib/modules/cli/vds.php -c synchronize
php /var/www/pakiti3/lib/modules/cli/calculateVulnerabilities.php

Cheers,
Kuba Mlčák

**Comment by tjones136** [comment]
Thanks for turning that out so quickly.  Even if it was on the way anyways.

Updated to latest version, because newer and therefore better, now getting the following:

# php /var/www/pakiti3/lib/modules/cli/vds.php -c synchronize
PHP Notice:  Undefined offset: 0 in /var/www/pakiti3/lib/modules/vds/sources/CveSubSources/Debian.php on line 50
PHP Fatal error:  Call to a member function getUri() on a non-object in /var/www/pakiti3/lib/modules/vds/sources/CveSubSources/Debian.php on line 50

There seems to be something about line 50 in Debian.php that my php binary just doesn't like.

**Comment by kouril** [comment]
The error should be fixed now, please pull the code and give it another try.

**Comment by tjones136** [comment]
That killed the error.  Thank you!

I am now able to pull and load OVAL data into my database.
