### ISSUE TITLE
Trouble adding repository

### ISSUE THREAD

**Issue by tjones136** [CESNET/pakiti3#53]
Have clients sending data and everything's going into the data base there.

Thanks to the project members who've helped me, I now have OVAL definitions streaming into my database as well. 

Having a bit of trouble getting my local repository added.

Tried using the same interface I used for adding OVAL data, system tried to add it as a source for CVE data. So, not quite what I was trying to accomplish.  Tried adding a repository definition to Repositories.xml and restarted my web server, just in case.  No change there.

From the command line I get:
php /var/www/pakiti3/lib/modules/cli/vds.php -c addSubSourceDef --sourceId 2 --subSourceId 1 --subSourceDefId 1 --defName RedHat --defUri http://server.example.com/yum/RedHat/
PHP Fatal error:  Call to a member function getName() on a non-object in /var/www/pakiti3/lib/modules/cli/vds.php on line 117

Line 117 looks like a fairly standard print statement, so I'm sort of stuck.

**Comment by tauceti2** [comment]
Hi tjones136,

Unfortunately there is no implemented support for repositories yet. Pakiti3 is now supporting just OVAL definitions from RH and DSA definitions from Debian.

Cheers,

Michal P.
