### ISSUE TITLE
Why not support HTTP for Debian OVAL

### ISSUE THREAD

**Issue by bluikko** [CESNET/pakiti3#66]
Debian provides OVAL data through HTTP similarly to RHEL and not just SVN, for example for 2017:
https://www.debian.org/security/oval/oval-definitions-2017.xml
Pakiti3 attempts to download them with SVN even if protocol in Pakiti3 VDS is set to an HTTPS URL like above example.
Why not support HTTPS for Debian OVAL data instead of always trying with SVN?

**Comment by tauceti2** [comment]
Hi,

AFAIK OVAL is not still officially supported by Debian. It also contains only Deb >7. When the Debian will announce that their OVAL definitions are official we will switch to it.

Cheers,

Michal P.

**Comment by bluikko** [comment]
I guess this issue is resolved with commit 6d73766 - did not test it yet.
