### ISSUE TITLE
No overview page for # updates/sec. upd/CVEs for all hosts like Pakiti2?

### ISSUE THREAD

**Issue by bluikko** [CESNET/pakiti3#67]
In Pakiti2 the hosts.php page shows a very useful single-page overview of all hosts and their kernel/# updates needed/# security updates needed/# CVEs.

In Pakiti3 the only way to see number of updates/security updates is to click an individual host and go to view a single report? The hosts.php lists only kernel, # reports and latest update - but no # updates/security updates/CVEs.

It would be very useful if hosts.php could show this (# updates/CVEs) data, otherwise an operator needs to click each host one by one (and check the reports) - or am I missing something here? It seems useless, nobody will click through all hosts one by one to see what they need?

**Comment by bluikko** [comment]
Have I misunderstood the purpose of Pakiti3 - it is not for reporting updates and CVEs for all clients like Pakiti2? Or is the functionality still incomplete since I do not see any place for configuring repositories either, just CVE/OVAL sources?

**Comment by kouril** [comment]
The design of Pakiti makes it possible to work with repositories, however the appropriate handler isn't implemented for Pakiti v3. Patches are welcome :-)

As for the overview page, it should improve shortly.

**Comment by kouril** [comment]
The current version of GUI displays tagged CVEs (i.e. those recognized important by the Pakiti admin).

As mentioned earlier, current implementation of the server supports only CVE's, checking information from repositories isn't implemented and we don't foresee to implement it in near future (given the resources we have), sorry.

I'm closing the issue, if you believe the current functions aren't enough for you, feel free to open it again but please elaborate more on your use-cases.

**Comment by bluikko** [comment]
The new overview page is great!
